In [1]:
import torch

In [3]:
x=torch.empty(5,3)
print(x)

tensor([[5.6015e-02, 4.4721e+21, 7.0000e+28],
        [8.1574e-33, 1.3563e-19, 1.6114e-19],
        [1.0889e+27, 1.7239e+25, 3.9133e-14],
        [1.3563e-19, 1.7753e+28, 1.3458e-14],
        [4.2016e+30, 1.4603e-19, 1.8728e+31]])


In [5]:
x=torch.rand(5,3)
print(x)

tensor([[0.0644, 0.1337, 0.2983],
        [0.3618, 0.0918, 0.0937],
        [0.7396, 0.4057, 0.2683],
        [0.5222, 0.7589, 0.4013],
        [0.5720, 0.8688, 0.7576]])


In [6]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x=torch.tensor([5,5,3])
print(x)

tensor([5, 5, 3])


x=x.new_ones(5,3,dtype=torch.float64)
print(x)

x=torch.rand_like(x,dtype=torch.float)
print(x)

In [33]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [34]:
y=torch.rand(5,3)
print(x+y)

tensor([[1.2551, 1.0693, 0.9386],
        [1.8420, 0.6093, 0.9004],
        [0.8553, 1.1398, 0.7956],
        [0.8237, 1.0124, 0.8110],
        [1.2323, 1.3590, 1.5593]])


In [35]:
print(torch.add(x,y))

tensor([[1.2551, 1.0693, 0.9386],
        [1.8420, 0.6093, 0.9004],
        [0.8553, 1.1398, 0.7956],
        [0.8237, 1.0124, 0.8110],
        [1.2323, 1.3590, 1.5593]])


In [36]:
result=torch.empty(5,3)
torch.add(x,y,out=result)
result

tensor([[1.2551, 1.0693, 0.9386],
        [1.8420, 0.6093, 0.9004],
        [0.8553, 1.1398, 0.7956],
        [0.8237, 1.0124, 0.8110],
        [1.2323, 1.3590, 1.5593]])

In [37]:
y.add_(x)
y

tensor([[1.2551, 1.0693, 0.9386],
        [1.8420, 0.6093, 0.9004],
        [0.8553, 1.1398, 0.7956],
        [0.8237, 1.0124, 0.8110],
        [1.2323, 1.3590, 1.5593]])

In [38]:
x

tensor([[0.5548, 0.2143, 0.2313],
        [0.9949, 0.1128, 0.2582],
        [0.5640, 0.4789, 0.7853],
        [0.6005, 0.1801, 0.7374],
        [0.6907, 0.6474, 0.9053]])

In [41]:
y=x[0,:]
y+=1
print(y)
print(x)

tensor([2.5548, 2.2143, 2.2313])
tensor([[2.5548, 2.2143, 2.2313],
        [0.9949, 0.1128, 0.2582],
        [0.5640, 0.4789, 0.7853],
        [0.6005, 0.1801, 0.7374],
        [0.6907, 0.6474, 0.9053]])


In [42]:
y=x.view(15)
z=x.view(-1,5)
print(x.size(),y.size(),z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [44]:
x+=1
print(x)
print(y)

tensor([[4.5548, 4.2143, 4.2313],
        [2.9949, 2.1128, 2.2582],
        [2.5640, 2.4789, 2.7853],
        [2.6005, 2.1801, 2.7374],
        [2.6907, 2.6474, 2.9053]])
tensor([4.5548, 4.2143, 4.2313, 2.9949, 2.1128, 2.2582, 2.5640, 2.4789, 2.7853,
        2.6005, 2.1801, 2.7374, 2.6907, 2.6474, 2.9053])


In [45]:
x_cp=x.clone().view(15)
x-=1
print(x)
print(x_cp)

tensor([[3.5548, 3.2143, 3.2313],
        [1.9949, 1.1128, 1.2582],
        [1.5640, 1.4789, 1.7853],
        [1.6005, 1.1801, 1.7374],
        [1.6907, 1.6474, 1.9053]])
tensor([4.5548, 4.2143, 4.2313, 2.9949, 2.1128, 2.2582, 2.5640, 2.4789, 2.7853,
        2.6005, 2.1801, 2.7374, 2.6907, 2.6474, 2.9053])


In [47]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([0.4851])
0.4851057827472687


In [52]:
x=torch.arange(1,3).view(1,2)
print(x)
y=torch.arange(1,4).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [55]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)
y=y+x
print(id(y)==id_before)

False


In [56]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)
y[:]=y+x
print(id(y)==id_before)

True


In [57]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)
torch.add(x,y,out=y)
print(id(y)==id_before)

True


In [58]:
a=torch.ones(5)
b=a.numpy()
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [60]:
a+=1
print(a,b)

tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [61]:
b+=1
print(a,b)

tensor([4., 4., 4., 4., 4.]) [4. 4. 4. 4. 4.]


In [62]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [64]:
a+=1
print(a,b)

[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [65]:
b+=1
print(a,b)

[4. 4. 4. 4. 4.] tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


In [66]:
c=torch.tensor(a)
a+=1
print(a,c)

[5. 5. 5. 5. 5.] tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


In [67]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)
