In [1]:
import torch
from torch import nn
from torch.nn import init

In [2]:
net=nn.Sequential(nn.Linear(4,3),nn.ReLU(),nn.Linear(3,1))

print(net)
X=torch.rand(2,4)
Y=net(X).sum()

Sequential(
  (0): Linear(in_features=4, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
)


In [4]:
print(type(net.named_parameters()))
for name,param in net.named_parameters():
    print(name,param.size())

<class 'generator'>
0.weight torch.Size([3, 4])
0.bias torch.Size([3])
2.weight torch.Size([1, 3])
2.bias torch.Size([1])


In [9]:
for name,param in net[0].named_parameters():
    print(name,param.size(),type(param))

weight torch.Size([3, 4]) <class 'torch.nn.parameter.Parameter'>
bias torch.Size([3]) <class 'torch.nn.parameter.Parameter'>


In [10]:
class MyModule(nn.Module):
    def __init__(self,**kwargs):
        super(MyModule,self).__init__(**kwargs)
        self.weight1=nn.Parameter(torch.rand(20,20))
        self.weight2=torch.rand(20,20)
    def forward(self,x):
        pass

In [11]:
n=MyModule()
for name,param in n.named_parameters():
    print(name)

weight1


In [18]:
weight_0=list(net[0].parameters())[0]

In [19]:
weight_0

Parameter containing:
tensor([[ 0.1569, -0.2629,  0.3522,  0.4503],
        [-0.1136, -0.0196,  0.0208,  0.0894],
        [-0.1095, -0.2642, -0.2581, -0.3135]], requires_grad=True)

In [21]:
print(weight_0.data)

tensor([[ 0.1569, -0.2629,  0.3522,  0.4503],
        [-0.1136, -0.0196,  0.0208,  0.0894],
        [-0.1095, -0.2642, -0.2581, -0.3135]])


In [22]:
print(weight_0.grad)

None


In [23]:
Y.backward()
print(weight_0.grad)

tensor([[-0.6582, -0.2386, -0.7567, -0.7215],
        [ 0.1918,  0.0696,  0.2205,  0.2103],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])


In [24]:
for name,param in net.named_parameters():
    if 'weight' in name:
        init.normal_(param,mean=0,std=0.01)
        print(name,param.data)

0.weight tensor([[-0.0053, -0.0095,  0.0047, -0.0188],
        [ 0.0135, -0.0013,  0.0050, -0.0029],
        [ 0.0027, -0.0071, -0.0008, -0.0046]])
2.weight tensor([[-0.0054, -0.0014,  0.0087]])


In [25]:
for name,param in net.named_parameters():
    if 'bias' in name:
        init.constant_(param,val=0)
        print(name,param.data)

0.bias tensor([0., 0., 0.])
2.bias tensor([0.])


In [26]:
def normal_(tensor,mean=0,std=0.01):
    with torch.no_grad():
        return tensor.normal_(mean,std)

In [27]:
def init_weight_(tensor):
    with torch.no_grad():
        tensor.uniform_(-10,10)
        tensor *=(tensor.abs()>=5).float()

In [28]:
for name,param in net.named_parameters():
    if 'weight' in name:
        init_weight_(param)
        print(name,param.data)

0.weight tensor([[-0.0000, -0.0000, -7.7041, -0.0000],
        [-5.6443, -0.0000, -9.7382,  9.6003],
        [-0.0000, -8.8805, -5.4787, -0.0000]])
2.weight tensor([[-0.0000, -0.0000, -7.8468]])


In [38]:
linear=nn.Linear(1,1,bias=False)
net=nn.Sequential(linear,linear)
print(net)
for name,param in net.named_parameters():
    init.constant_(param,val=3)
    print(name,param.data)

Sequential(
  (0): Linear(in_features=1, out_features=1, bias=False)
  (1): Linear(in_features=1, out_features=1, bias=False)
)
0.weight tensor([[3.]])


In [39]:
print(id(net[0])==id(net[1]))
print(id(net[0].weight)==id(net[1].weight))

True
True


In [40]:
x=torch.ones(1,1)
y=net(x).sum()
print(y)

tensor(9., grad_fn=<SumBackward0>)


In [41]:
y.backward()
print(net[0].weight.grad)

tensor([[6.]])
