In [1]:
!nvidia-smi

Wed Nov 20 06:49:15 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.31       Driver Version: 440.31       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce MX250       Off  | 00000000:02:00.0 Off |                  N/A |
| N/A   47C    P0    N/A /  N/A |      0MiB /  2002MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [2]:
import torch
from torch import nn

In [3]:
torch.cuda.is_available()

True

In [4]:
torch.cuda.device_count()

1

In [5]:
torch.cuda.current_device()

0

In [6]:
torch.cuda.get_device_name(0)

'GeForce MX250'

In [8]:
x=torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [9]:
x=x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [10]:
x.device

device(type='cuda', index=0)

In [11]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x=torch.tensor([1,2,3],device=device)
x

tensor([1, 2, 3], device='cuda:0')

In [13]:
y=x**2
y

tensor([1, 4, 9], device='cuda:0')

In [14]:
z=y+x.cpu()

RuntimeError: expected device cuda:0 but got device cpu

In [15]:
net=nn.Linear(3,1)
list(net.parameters())[0].device

device(type='cpu')

In [16]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [17]:
x=torch.rand(2,3).cuda()
net(x)

tensor([[0.1438],
        [0.3595]], device='cuda:0', grad_fn=<AddmmBackward>)